services:
  - type: web
    name: galvaniy-labs
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: EMAIL_USER
        value: galvanytech@gmail.com
      - key: EMAIL_PASS
        sync: false
    plan: free
